### PR TITLE
try fixes and understanding the problem ... 

### PR DESCRIPTION
**Pull request by ngam**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mkitti** [comment]
This passes?

**Comment by h-vetinari** [comment]
> I see a lot of clobber warnings. 

The reason for this is most likely as described [here](https://github.com/conda-forge/pysr-feedstock/pull/85#issuecomment-1576035778), i.e. reinstallation of numpy.

**Comment by MilesCranmer** [comment]
Once this merges: https://github.com/JuliaPy/PyCall.jl/pull/1040 we can disable the re-installation with a build flag. Then hopefully the build warnings will disappear.

**Comment by MilesCranmer** [comment]
@conda-forge-admin, please rerender

**Comment by MilesCranmer** [comment]
Not sure if this is a clue, but with the `libstdcxx-ng<13` setting in `run_constraints:`, the mamba build is now working, but the conda build fails:

https://github.com/MilesCranmer/PySR/actions/runs/5242217963

**Comment by MilesCranmer** [comment]
Once this is merged: https://github.com/JuliaRegistries/General/pull/85755

Then we can re-run these tests (need to bump build number), and see if it solves the clobber problem

**Comment by MilesCranmer** [comment]
Cool, it looks like the clobber issue is gone? Are there any other warnings we need to worry about?

**Comment by MilesCranmer** [comment]
Fingers crossed.

**Comment by h-vetinari** [comment]
This looks better now, though there's what looks like a segfault in one of the linux jobs on `main`.

Also, this doesn't look great:
```
WARNING (pysr,share/pysr/depot/artifacts/9f6f87cc2114df918ff9c21dff9572f690e7dab2/lib/libLLVMExtra-14.so): runpaths ['$ORIGIN'] found in /home/conda/feedstock_root/build_artifacts/pysr_1687299957695/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/share/pysr/depot/artifacts/9f6f87cc2114df918ff9c21dff9572f690e7dab2/lib/libLLVMExtra-14.so
WARNING (pysr,share/pysr/depot/artifacts/9f6f87cc2114df918ff9c21dff9572f690e7dab2/lib/libLLVMExtra-14.so): $RPATH/libLLVM-14jl.so not found in packages, sysroot(s) nor the missing_dso_whitelist.
.. is this binary repackaging?
WARNING (pysr,share/pysr/depot/artifacts/9f6f87cc2114df918ff9c21dff9572f690e7dab2/lib/libLLVMExtra-14.so): /lib64/libstdc++.so.6 not found in packages, sysroot(s) nor the missing_dso_whitelist.
.. is this binary repackaging?
WARNING (pysr,share/pysr/depot/artifacts/9f6f87cc2114df918ff9c21dff9572f690e7dab2/lib/libLLVMExtra-14.so): /lib64/libm.so.6 not found in packages, sysroot(s) nor the missing_dso_whitelist.
.. is this binary repackaging?
WARNING (pysr,share/pysr/depot/artifacts/9f6f87cc2114df918ff9c21dff9572f690e7dab2/lib/libLLVMExtra-14.so): /lib64/libgcc_s.so.1 not found in packages, sysroot(s) nor the missing_dso_whitelist.
.. is this binary repackaging?
WARNING (pysr,share/pysr/depot/artifacts/9f6f87cc2114df918ff9c21dff9572f690e7dab2/lib/libLLVMExtra-14.so): /lib64/libc.so.6 not found in packages, sysroot(s) nor the missing_dso_whitelist.
.. is this binary repackaging?
```

I don't know where `libLLVMExtra-14.so` comes from - I help package LLVM for conda-forge, but I've never seen that library, and I cannot [find](https://github.com/search?q=repo%3Allvm%2Fllvm-project+%2F%28lib%29%3FLLVMExtra%2F&type=code) it upstream either.

**Comment by MilesCranmer** [comment]
Regarding the segfault, the full set of tests is fairly compute/memory intensive compared to the compute used in the build jobs. So maybe we could use a lighter test, since we just want a smoke test for the integration all working.

I’m also unsure why the OSX jobs freeze during the precompilation: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=731490&view=logs&j=a8dee1cf-d17f-5cb0-b53f-4a93dfdbfb0c&t=d9dbf137-9a7f-5666-c60c-9e1b2fc31445 — this seems repeatable, and only occurs on Python 3.9+OSX…

**Pull request merged**
